import { h } from 'vue';
import { aliases, mdi } from 'vuetify/iconsets/mdi-svg';
import {
  mdiAccountGroup,
  mdiAlertCircle,
  mdiArrowRight,
  mdiBookOpenVariant,
  mdiCalculatorVariant,
  mdiCertificate,
  mdiChartBar,
  mdiChartTimelineVariant,
  mdiCheckCircleOutline,
  mdiCheckDecagram,
  mdiCheckboxBlankOutline,
  mdiClose,
  mdiCompass,
  mdiContentCopy,
  mdiDatabase,
  mdiDatabaseCheck,
  mdiDatabaseCheckOutline,
  mdiDatabaseOff,
  mdiDatabaseSearch,
  mdiDeleteSweep,
  mdiDna,
  mdiDownload,
  mdiFileDelimited,
  mdiFileExcel,
  mdiFormatListBulletedSquare,
  mdiFormatQuoteClose,
  mdiGavel,
  mdiGithub,
  mdiInformation,
  mdiInformationOutline,
  mdiMagnify,
  mdiMenu,
  mdiNewBox,
  mdiNewspaperVariantOutline,
  mdiNumeric1Circle,
  mdiNumeric2Circle,
  mdiOpenInNew,
  mdiPencil,
  mdiPercent,
  mdiPlusCircleOutline,
  mdiRefresh,
  mdiShareVariant,
  mdiTextBoxOutline,
  mdiWeatherNight,
  mdiWhiteBalanceSunny,
} from '@mdi/js';

// Keep this map explicit so unused SVG paths are removed from the production build.
// The coverage test checks icons in Vue templates, JavaScript and JSON configuration.
export const iconPaths = {
  'mdi-account-group': mdiAccountGroup,
  'mdi-alert-circle': mdiAlertCircle,
  'mdi-arrow-right': mdiArrowRight,
  'mdi-book-open-variant': mdiBookOpenVariant,
  'mdi-calculator-variant': mdiCalculatorVariant,
  'mdi-certificate': mdiCertificate,
  'mdi-chart-bar': mdiChartBar,
  'mdi-chart-timeline-variant': mdiChartTimelineVariant,
  'mdi-check-circle-outline': mdiCheckCircleOutline,
  'mdi-check-decagram': mdiCheckDecagram,
  'mdi-checkbox-blank-outline': mdiCheckboxBlankOutline,
  'mdi-close': mdiClose,
  'mdi-compass': mdiCompass,
  'mdi-content-copy': mdiContentCopy,
  'mdi-database': mdiDatabase,
  'mdi-database-check': mdiDatabaseCheck,
  'mdi-database-check-outline': mdiDatabaseCheckOutline,
  'mdi-database-off': mdiDatabaseOff,
  'mdi-database-search': mdiDatabaseSearch,
  'mdi-delete-sweep': mdiDeleteSweep,
  'mdi-dna': mdiDna,
  'mdi-download': mdiDownload,
  'mdi-file-delimited': mdiFileDelimited,
  'mdi-file-excel': mdiFileExcel,
  'mdi-format-list-bulleted-square': mdiFormatListBulletedSquare,
  'mdi-format-quote-close': mdiFormatQuoteClose,
  'mdi-gavel': mdiGavel,
  'mdi-github': mdiGithub,
  'mdi-information': mdiInformation,
  'mdi-information-outline': mdiInformationOutline,
  'mdi-magnify': mdiMagnify,
  'mdi-menu': mdiMenu,
  'mdi-new-box': mdiNewBox,
  'mdi-newspaper-variant-outline': mdiNewspaperVariantOutline,
  'mdi-numeric-1-circle': mdiNumeric1Circle,
  'mdi-numeric-2-circle': mdiNumeric2Circle,
  'mdi-open-in-new': mdiOpenInNew,
  'mdi-pencil': mdiPencil,
  'mdi-percent': mdiPercent,
  'mdi-plus-circle-outline': mdiPlusCircleOutline,
  'mdi-refresh': mdiRefresh,
  'mdi-share-variant': mdiShareVariant,
  'mdi-text-box-outline': mdiTextBoxOutline,
  'mdi-weather-night': mdiWeatherNight,
  'mdi-white-balance-sunny': mdiWhiteBalanceSunny,
};

export const iconConfig = {
  defaultSet: 'app',
  aliases,
  sets: {
    app: {
      component: (props) =>
        h(mdi.component, {
          ...props,
          // Preserve icon selectors used by guided tours and component styles.
          class: props.icon,
          icon: iconPaths[props.icon] || props.icon,
        }),
    },
  },
};
