# .github/workflows/gh-pages.yml

name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: ["Semantic Release"] # <-- CHANGE: Name of your release workflow
    types:
      - completed # <-- Only run when the release workflow finishes
    branches:
      - main # <-- Only run if the release workflow ran on the main branch

jobs:
  # Build job: Install dependencies, build the application, and upload the artifact
  build:
    name: Build Application
    # IMPORTANT: Add this condition to only build if the triggering workflow was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # IMPORTANT: Checkout the specific commit the release workflow ran on
        with:
           ref: ${{ github.event.workflow_run.head_sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        env:
          NODE_OPTIONS: --no-experimental-fetch --openssl-legacy-provider
        run: npm run build

      - name: Prepare 404 page for SPA routing
        run: cp dist/index.html dist/404.html

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  # Deploy job: Deploy the uploaded artifact to GitHub Pages
  deploy:
    name: Deploy to Pages
    needs: build # Depends on the build job
    # IMPORTANT: Add this condition here too
    if: ${{ needs.build.result == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    concurrency:
      # Use head_sha for concurrency to group runs related to the specific commit
      group: "pages-${{ github.event.workflow_run.head_sha }}"
      cancel-in-progress: true # Okay to cancel if a newer commit triggered a release
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4