name: Publish Wiki

on:
  push:
    branches:
      - main # Or your default branch
    paths:
      - 'docs/wiki/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push to the wiki repository
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Push docs/wiki content to Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          # The GITHUB_TOKEN is automatically available to the workflow
          # and has the necessary permissions due to `permissions: contents: write` above.
          token: ${{ secrets.GITHUB_TOKEN }}
          # Path to the directory containing your wiki files in the main repository
          path: docs/wiki
          # The commit message for the wiki update - REMOVED as it's an invalid input for v4
#         commit_message: "docs: Update wiki content from main repository"
